import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import Providers from '@/components/providers'
import './globals.css'
import { Toaster } from "@/components/ui/sonner"
import CreateCloneButton from '@/components/create-clone'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en' className='scroll-smooth'>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className='flex h-16 items-center justify-end gap-4 p-4'>
            <SignedOut>
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              <CreateCloneButton />
              <UserButton />
            </SignedIn>
          </header>
          <Providers>{children}</Providers>
          <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>
  )
}
